#!/usr/bin/env bash
set -e

COVEROUT="coverage"

if ! [ -d $COVEROUT ]; then
    mkdir $COVEROUT
fi

go test -v -coverprofile=${COVEROUT}/twitter.out ./twitter

go tool cover -html=${COVEROUT}/twitter.out